"""empty message

Revision ID: cae29f34f50b
Revises: a46664f3304d
Create Date: 2020-02-17 22:59:34.559792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cae29f34f50b'
down_revision = 'a46664f3304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
