"""empty message

Revision ID: 186c6f0d376c
Revises: 9e2a58871d2e
Create Date: 2020-02-27 19:59:30.024984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186c6f0d376c'
down_revision = '9e2a58871d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CMS_User_Role',
    sa.Column('CMSRole_id', sa.Integer(), nullable=False),
    sa.Column('CMSUser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CMSRole_id'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['CMSUser_id'], ['cms_user.id'], ),
    sa.PrimaryKeyConstraint('CMSRole_id', 'CMSUser_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CMS_User_Role')
    op.drop_table('cms_role')
    # ### end Alembic commands ###
