"""empty message

Revision ID: 9e2a58871d2e
Revises: 7a192af1ddba
Create Date: 2020-02-27 19:57:59.097783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e2a58871d2e'
down_revision = '7a192af1ddba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cms_user_role')
    op.drop_table('cm_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('permissions', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('cms_user_role',
    sa.Column('CMSRole_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('CMSUser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CMSRole_id'], ['cm_role.id'], name='cms_user_role_ibfk_1'),
    sa.ForeignKeyConstraint(['CMSUser_id'], ['cms_user.id'], name='cms_user_role_ibfk_2'),
    sa.PrimaryKeyConstraint('CMSRole_id', 'CMSUser_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
