"""empty message

Revision ID: bacb0a87388a
Revises: cae29f34f50b
Create Date: 2020-02-17 23:01:05.353985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacb0a87388a'
down_revision = 'cae29f34f50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###
